# Generated by Django 4.2.7 on 2023-11-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("empresa", models.CharField(blank=True, max_length=100, null=True)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("marcado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tempo_preparo", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pedido", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pendente", "Pendente"), ("Concluído", "Concluído")],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fazenda.cliente",
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(
                        through="fazenda.ItemPedido", to="fazenda.produto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itempedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fazenda.pedido"
            ),
        ),
        migrations.AddField(
            model_name="itempedido",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fazenda.produto"
            ),
        ),
    ]
