# Generated by Django 4.2.7 on 2023-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="data_pedido",
            field=models.DateField(auto_now_add=True),
        ),
    ]
