# Generated by Django 4.2.7 on 2023-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fazenda", "0003_pedido_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="marcado",
            field=models.BooleanField(default=False),
        ),
    ]
